import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  weight: ["400","500","600","700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Property Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`min-h-full font-dm-sans flex flex-col ${dmSans.variable}`}>{children}</body>
    </html>
  );
}
